ARG OPENSEARCH_VERSION

FROM opensearchproject/opensearch:$OPENSEARCH_VERSION
ARG ELK_VERSION

# Adding custom plugin here, remove if you're not needed
# Replace it with the plugins of your choice
# TODO need to fix with proper plugin built for OpenSearch
#RUN /usr/share/opensearch/bin/opensearch-plugin install file:////Users/konstantinp/projects/elasticsearch-ingest-opennlp/build/distributions/ingest-opennlp-7.10.2.1-SNAPSHOT.zip
