ARG OPENSEARCH_VERSION

FROM opensearchproject/opensearch:$OPENSEARCH_VERSION

# Adding custom plugin here, remove if you're not needed
# Replace it with the plugins of your choice
# Example: Install a custom plugin from a URL or local file
# RUN /usr/share/opensearch/bin/opensearch-plugin install <plugin-url-or-path>
