version: '3.7'
services:
  odfe-node1:
    build:
      context: .
      args:
        ELK_VERSION: ${ELK_VERSION}
        OPEN_DISTRO_VERSION: ${OPEN_DISTRO_VERSION}
    image: odfe:${OPEN_DISTRO_VERSION}
    container_name: odfe-node1
    environment:
      - node.name=odfe-node1
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
#      - opendistro_security.ssl.http.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - discovery.seed_hosts=odfe-node1,odfe-node2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data1:/usr/share/elasticsearch/data
      #- ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      #- ./esnode.pem:/usr/share/elasticsearch/config/esnode.pem
      #- ./esnode-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
      #- ./kirk.pem:/usr/share/elasticsearch/config/kirk.pem
      #- ./kirk-key.pem:/usr/share/elasticsearch/config/kirk-key.pem
      #- ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
    ports:
      - "9200:9200"
    networks:
      - odfe-net
  odfe-node2:
    image: odfe:${OPEN_DISTRO_VERSION}
    container_name: odfe-node2
    environment:
      - node.name=odfe-node2
      - cluster.name=odfe-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=odfe-node1,odfe-node2
      - discovery.seed_hosts=odfe-node1,odfe-node2
#      - opendistro_security.ssl.http.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - odfe-data2:/usr/share/elasticsearch/data
      #- ./root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      #- ./esnode.pem:/usr/share/elasticsearch/config/esnode.pem
      #- ./esnode-key.pem:/usr/share/elasticsearch/config/esnode-key.pem
      #- ./kirk.pem:/usr/share/elasticsearch/config/kirk.pem
      #- ./kirk-key.pem:/usr/share/elasticsearch/config/kirk-key.pem
      #- ./custom-elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/
    ports:
      - "9201:9200"
    networks:
      - odfe-net
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:${OPEN_DISTRO_VERSION}
    container_name: odfe-kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
    #volumes:
      #- ./custom-kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
