#!/usr/bin/env python3
"""Index model-backed embedding JSON generated by data/generate_embeddings.py."""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from search.capabilities import detect  # noqa: E402
from search.config import resolve  # noqa: E402
from search.connection import ConnectionFailed, EsError  # noqa: E402
from search.loader import bulk_index  # noqa: E402
from search.mappings import VECTOR_FIELD, index_body  # noqa: E402


def parse_args():
    parser = argparse.ArgumentParser(description="Index generated movie embedding JSON")
    parser.add_argument("--input", default="data/movies_enriched_with_embeddings.json")
    parser.add_argument("--index", default="movies-embeddings")
    parser.add_argument(
        "--model", default="sentence-transformers", help="recorded in _meta"
    )
    parser.add_argument("--url")
    parser.add_argument("--user")
    parser.add_argument("--password")
    parser.add_argument("--insecure", action="store_true")
    parser.add_argument("--no-auth", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Input file not found: {input_path}")
        print("Generate it first, for example:")
        print("  python data/generate_embeddings.py --limit 100")
        return 1

    with input_path.open(encoding="utf-8") as input_file:
        documents = json.load(input_file)
    dims = len(documents[0][VECTOR_FIELD])

    try:
        client = resolve(
            url=args.url,
            user=args.user,
            password=args.password,
            no_auth=args.no_auth,
            insecure=args.insecure,
        ).client()
        caps = detect(client)
        meta = {
            "foe": {
                "embedding": {"backend": "external", "model": args.model, "dims": dims}
            }
        }
        client.delete(f"/{args.index}", ok=(404,))
        client.put(f"/{args.index}", index_body(caps, meta, dims))
        loaded, errors = bulk_index(client, args.index, documents)
        client.post(f"/{args.index}/_refresh")
    except (ConnectionFailed, EsError) as exc:
        print(f"Error: {exc}")
        return 1
    print(f"Indexed {loaded}/{len(documents)} documents into {args.index}")
    if errors:
        print(f"Errors by type: {errors}")
    return 0 if loaded == len(documents) else 1


if __name__ == "__main__":
    sys.exit(main())
