#!/usr/bin/env python3
"""Index model-backed embedding JSON generated by data/generate_embeddings.py."""

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from data.load_data import MOVIES_MAPPING_WITH_EMBEDDINGS, DataLoader  # noqa: E402


def parse_args():
    parser = argparse.ArgumentParser(description="Index generated movie embedding JSON")
    parser.add_argument("--input", default="data/movies_enriched_with_embeddings.json")
    parser.add_argument("--index", default="movies-embeddings")
    parser.add_argument(
        "--url", default=os.getenv("ELASTICSEARCH_URL", "http://localhost:9200")
    )
    parser.add_argument("--user", default=os.getenv("ELASTIC_USER", "elastic"))
    parser.add_argument("--password", default=os.getenv("ELASTIC_PASSWORD", "elastic"))
    parser.add_argument("--insecure", action="store_true")
    parser.add_argument("--no-auth", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Input file not found: {input_path}")
        print("Generate it first, for example:")
        print("  python data/generate_embeddings.py --limit 100")
        return 1

    with input_path.open(encoding="utf-8") as input_file:
        documents = json.load(input_file)

    auth = None if args.no_auth else (args.user, args.password)
    loader = DataLoader(args.url, auth=auth, verify_ssl=not args.insecure)
    if not loader.check_connection():
        return 1

    if not loader.create_index(args.index, MOVIES_MAPPING_WITH_EMBEDDINGS):
        return 1

    loaded = loader.bulk_load(args.index, documents)
    loader.refresh(args.index)
    print(f"Indexed {loaded}/{len(documents)} documents into {args.index}")
    return 0 if loaded == len(documents) else 1


if __name__ == "__main__":
    sys.exit(main())
